### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by camechis** [gradle-clojure/gradle-clojure#24]
Hey guys, I just discovered this project.  I  have been wanting a nice gradle clojure build system for awhile.

1.  What happened with graclj ?
2.  Are you guys working on it pretty actively or just on freetime ?
3.  What are the core set of features your looking to get done ?

**Comment by jszakmeister** [comment]
> 1. What happened with graclj ?

Gradle [backpedaled](https://blog.gradle.org/state-and-future-of-the-gradle-software-model) on their software model and have deprecated with it slated to be removed entirely in Gradle 6, IIRC.  As such, it doesn't make sense for graclj to continue, since it was based on that model.  Andrew might have more to say about it, but that's the situation as I understand it.

> 2. Are you guys working on it pretty actively or just on freetime ?

We're volunteers, so it's all on free time.  That said, we all want to see solid support in Gradle for Clojure.  There are definitely a few challenges though.  For instance, this like firing up a REPL are interesting when it's a daemon whose running the task.  We're going to have to work out some things with the core Gradle team to figure out the best way forward here.

> 3. What are the core set of features your looking to get done ?

Right now, we want to be able to build Clojure code in a polyglot environment following the guidelines set forth by the Gradle team.  There's some work in the queue to move the compilation task off to workers which will save some compilation time.  For the future, it's pretty open right now.  It'd be nice to solve the REPL problem, and maybe add support for some other test frameworks.  Additionally, we'd like to round out support by also allowing ClojureScript code to be built via Gradle as well.  It might also be nice to provide incremental compilation support, but there's some debate as to how feasible that really is.

So there's some work to be done, but it's not crazy.  The great thing about being in the Gradle environment is that things already exist for packaging and other miscellaneous tasks you might have.  So I don't think the list is long here. :-)  I think the harder problem is staying on top of changes in Gradle, and leveraging any new features to help builds.

Also, I think there's some hope that other plugins can build on top of this plugin to provide extra support for various tools (generative testing, generating documentation, archetypes to help start new projects, etc.).

I hope that answers your questions.

**Comment by camechis** [comment]
Awesome, answers all my questions.  If i have some time i will look to contribute some where I can.

**Comment by ajoberstar** [comment]
Just wanted to second everything @jszakmeister. That's a good summary of what we're up to. We'd welcome the help if you have time.
